= IntelliJ Plugin

This plugin provide some automation to approve files from Approvals.

Key features:

* Approve a 'received' file
* Approve all 'received' file in a directory
* Compare 'received' file and 'approved' file
* Switch between Java class/method and the associated approved file

This plugin is a beta version.
You can find the link:https://github.com/DocAsTest/doc-as-test-intellij-plugin/releases/latest[last release] in the repository.
The plugin is not in the marketplace, so you have to deploy it to your IntelliJ from .jar you downloaded.

== Development

=== Release

There is a Github action to create a release.
To launch a new one, you have to go to link:https://github.com/DocAsTest/doc-as-test-intellij-plugin/actions/workflows/release.yml[Github > Actions > Release] and `Run workflow` on main branch.

=== Changelog

* link:https://keepachangelog.com[]

* link:https://github.com/JetBrains/gradle-changelog-plugin/blob/main/README.md[Gradle plugin]

.Labels used
* *Added*: for new features.
* *Changed*: for changes in existing functionality.
* Deprecated: for soon-to-be removed features.
* *Removed*: for now removed features.
* *Fixed*: for any bug fixes.
* *Security*: in case of vulnerabilities.

During development, add manually changes in the `[Unreleased]` section of the `CHANGELOG.md` file.
This section will become automatically the text of the release version.
It's configure in the `release` part in the `build.gradle`.


=== Resources

* link:https://plugins.jetbrains.com/docs/intellij/welcome.html[]
* link:https://www.baeldung.com/intellij-new-custom-plugin[]
* link:https://intellij-support.jetbrains.com/hc/en-us/community/topics/200366979-IntelliJ-IDEA-Open-API-and-Plugin-Development?__cf_chl_captcha_tk__=pmd_k4Tjotbjb.Q5.2un_F6Gl_pgXolke818kVkkYWb8ISc-1632380657-0-gqNtZGzNA1CjcnBszQk9[IntelliJ IDEA Open API and Plugin Development]

=== Versions

* link:https://plugins.jetbrains.com/docs/intellij/build-number-ranges.html#intellij-platform-based-products-of-recent-ide-versions[IntelliJ Platform Based Products of Recent IDE Versions]

== Tests

We use `JUnit4`, so classes must be annotated with `@RunWith(JUnit4.class)` and methods with `@Test` as described in `com.intellij.testFramework.UsefulTestCase`.